name: Verdigris' Book
description: Record any useful things or moments.
meta_description: "A Jekyll Site, belongs to Verdigris."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://zhangyanwei.github.com'
# google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://zhangyanwei.github.com'
author:         'Verdigris'
