name: Zhangyaiwei's Blog
description: Record any useful things or moments.
meta_description: "\"这个人太懒了，没能把所有都留下\""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://www.luogu.com.cn/user/684245'
# google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.luogu.com.cn/user/684245'
author:         'Zhangyaiwei'
